/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.OrdersController;
import entities.Order;
import entities.Product;
import entities.User;
import enums.OrderStatus;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import java.text.SimpleDateFormat;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import utils.Result;
import utils.ResultData;

/**
 *
 * @author Paulo
 */
public class OrderList extends javax.swing.JFrame {

    /**
     * Creates new form OrderList
     */
    private OrdersController _ordersController;
    
    private Order _orderOpenedCurrent;
    private DefaultTableModel _ordersOpenedTableModel;
    
    public OrderList(OrdersController ordersController) {
        initComponents();
        _ordersController = ordersController;

        updateTitle(); 
    }
    
    private void updateTitle() {
        User currentUser = _ordersController.getCurrentUser();
        setTitle("JPedidos - Gerenciar Pedidos (" + currentUser.getRoleString() + ")");
    }
    
    private void setOrderOpened(Order order) {
        _orderOpenedCurrent = order;
    }
    
    private void displayResult(Result result) {
        JOptionPane.showMessageDialog(this, result.getErrorMessage(), "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
        
    private void orderOpenedTableEvents() {
        ListSelectionModel model = tbl_list_opened.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = tbl_list_opened.getSelectedRow();
                if (row == -1) {
                    setOrderOpened(null);
                    return;
                }
                int id = getTableIdByIndex(_ordersOpenedTableModel, row);
                ResultData<Order> result = _ordersController.getById(id);
                if (result.hasError()){
                    displayResult(Result.error(result.getErrorMessage()));
                    return;
                }
                setOrderOpened(result.getData());
            }
        });
    }
    
    private void clearOrderOpenedTable() {
        _ordersOpenedTableModel.setRowCount(0);
    }
    
    private void clearOrderOpenedSelection() {
        tbl_list_opened.clearSelection();
        setOrderOpened(null);  
    }
    
    private int getTableIdByIndex(DefaultTableModel model, int index) {
        Object raw = model.getValueAt(index, 0);
        return Integer.parseInt(raw.toString());
    }    
    
    private ArrayList<Object> getOrderOpenedColumnsData(Order order) {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        ArrayList<Object> columns = new ArrayList<>();
        columns.add(order.getId());
        columns.add(order.getCustomer().getName());
        columns.add(order.getCustomer().getPhone());
        columns.add(String.format("%.2f", order.getTotal()).replace('.', ','));
        columns.add(df.format(order.getOpenDate()));
        return columns;
    }
    
    private void addRowOrderOpenedTable(Order order) {
        ArrayList<Object> columnsData = getOrderOpenedColumnsData(order);
        _ordersOpenedTableModel.addRow(columnsData.toArray());
    }
    
    private void removeRowOrderOpenedTable(Order order) {
        int index = getRowIndexWithId(_ordersOpenedTableModel, order.getId());
        _ordersOpenedTableModel.removeRow(index);
    }
    
    private int getRowIndexWithId(DefaultTableModel model, int id) {
        for (int row = 0; row < model.getRowCount(); row++){
            Object raw = model.getValueAt(row, 0);
            int rowId = Integer.parseInt(raw.toString());
            if (rowId == id) return row;
        }
        return -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_order_opened = new javax.swing.JTabbedPane();
        scroll = new javax.swing.JScrollPane();
        tbl_list_opened = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl_list_opened.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "Telefone do Cliente", "Valor Total", "Data/Hora de Abertura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scroll.setViewportView(tbl_list_opened);

        tab_order_opened.addTab("Pedidos Abertos", scroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_order_opened, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_order_opened, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        _ordersOpenedTableModel = (DefaultTableModel)tbl_list_opened.getModel();                       
        
        orderOpenedTableEvents();
        clearOrderOpenedTable();
        clearOrderOpenedSelection();
        
        ResultData<ArrayList<Order>> result = _ordersController.getAll();
        if (result.hasError()){
            displayResult(Result.error(result.getErrorMessage()));
            return;
        }
        
        for (Order order : result.getData()) {
            if (order.getStatus() == OrderStatus.Open)
                addRowOrderOpenedTable(order);
        }
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTabbedPane tab_order_opened;
    private javax.swing.JTable tbl_list_opened;
    // End of variables declaration//GEN-END:variables
}
