/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.UsersController;
import entities.User;
import enums.Role;
import java.util.ArrayList;
import static java.util.Arrays.asList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import models.SelectOption;
import models.SelectRole;
import utils.Result;
import utils.ResultData;

/**
 *
 * @author Paulo
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    private UsersController _usersController;

    private User _userCurrent;
    private List<SelectRole> _roles;
    private DefaultTableModel _userTableModel;
    
    public UserForm(UsersController usersController) {
        initComponents();
        _usersController = usersController;
        
        loadSelectFields();
        updateTitle();  
    }
    
    private void updateTitle() {
        User currentUser = _usersController.getCurrentUser();
        setTitle("JPedidos - Gerenciar Usuários (" + currentUser.getRoleString() + ")");
    }
    
    private void loadSelectFields() {        
        cb_role.removeAllItems();
        
        _roles = asList(
            new SelectRole(Role.Admin, "Admin"),
            new SelectRole(Role.Funcionario, "Funcionário"),
            new SelectRole(Role.Gerente, "Gerente")
        );
        
        for (SelectRole role : _roles)
            cb_role.addItem(role);  
    }
    
    private User getUser() {
        User user = _userCurrent != null
            ? _userCurrent
            : new User();
        
        user.setName(txt_name.getText());
        user.setLogin(txt_login.getText());
        user.setEmail(txt_email.getText());
        SelectRole roleSelected = cb_role.getSelectedItem() != null
            ? (SelectRole)cb_role.getSelectedItem()
            : new SelectRole();
        user.setRole(roleSelected.value);
        
        return user;
    }
    
    private void setUser(User user) {
        _userCurrent = user;
        txt_name.setText(user.getName());
        txt_login.setText(user.getLogin());
        txt_email.setText(user.getEmail());
        cb_role.getModel().setSelectedItem(getRoleSelected(user.getRole()));
    }
    
    private SelectRole getRoleSelected(Role role) {
        for (SelectRole sr : _roles) {
            if (sr.value == role) return sr;
        }
        
        return new SelectRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_fields = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new java.awt.TextField();
        lbl_login = new javax.swing.JLabel();
        txt_login = new java.awt.TextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new java.awt.TextField();
        lbl_role = new javax.swing.JLabel();
        cb_role = new javax.swing.JComboBox<>();
        pnl_actions = new javax.swing.JPanel();
        btn_clear = new javax.swing.JButton();
        btn_change_key = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_trash = new javax.swing.JButton();
        list_scroll = new javax.swing.JScrollPane();
        tbl_list = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JPedidos - Usuários");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_name.setText("Nome:");

        txt_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_name.setName("txt_name"); // NOI18N

        lbl_login.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_login.setText("Login:");

        txt_login.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_login.setName("txt_login"); // NOI18N

        lbl_email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_email.setText("Email:");

        txt_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_email.setName("txt_name"); // NOI18N

        lbl_role.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_role.setText("Papel:");

        cb_role.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnl_fieldsLayout = new javax.swing.GroupLayout(pnl_fields);
        pnl_fields.setLayout(pnl_fieldsLayout);
        pnl_fieldsLayout.setHorizontalGroup(
            pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fieldsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_name)
                    .addComponent(lbl_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fieldsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbl_login))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_fieldsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_role)))
                .addGap(18, 18, 18)
                .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_login, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(cb_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnl_fieldsLayout.setVerticalGroup(
            pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fieldsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_login, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(27, 27, 27)
                .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_role))
                    .addGroup(pnl_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_email)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btn_clear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paulo\\Desktop\\Cursos\\UTFPR\\7º Semestre\\Oficina de Integração 2\\JPedidos\\src\\main\\java\\assets\\clean-48.png")); // NOI18N
        btn_clear.setName("btn_clear"); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_change_key.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paulo\\Desktop\\Cursos\\UTFPR\\7º Semestre\\Oficina de Integração 2\\JPedidos\\src\\main\\java\\assets\\key-48.png")); // NOI18N
        btn_change_key.setEnabled(false);
        btn_change_key.setName("btn_clear"); // NOI18N
        btn_change_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_keyActionPerformed(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paulo\\Desktop\\Cursos\\UTFPR\\7º Semestre\\Oficina de Integração 2\\JPedidos\\src\\main\\java\\assets\\save-all-48.png")); // NOI18N
        btn_save.setName("btn_add"); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_trash.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paulo\\Desktop\\Cursos\\UTFPR\\7º Semestre\\Oficina de Integração 2\\JPedidos\\src\\main\\java\\assets\\trash-48.png")); // NOI18N
        btn_trash.setEnabled(false);
        btn_trash.setName("btn_add"); // NOI18N
        btn_trash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_actionsLayout = new javax.swing.GroupLayout(pnl_actions);
        pnl_actions.setLayout(pnl_actionsLayout);
        pnl_actionsLayout.setHorizontalGroup(
            pnl_actionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actionsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_change_key, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnl_actionsLayout.setVerticalGroup(
            pnl_actionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_actionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_actionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_change_key, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_list.setName("tbl_list"); // NOI18N
        list_scroll.setViewportView(tbl_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list_scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
            .addComponent(pnl_actions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_fields, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_actions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        User user = getUser();
        boolean byInsert = user.getId() == 0;
        String rawPassword = null;
        if (byInsert) {
            rawPassword = _usersController.generatePassword();
            user.setPasswordTemporary(true);
            user.setRawPassword(rawPassword);
        }
        Result result = byInsert
            ? _usersController.create(user)
            : _usersController.update(user);
                
        if (result.hasError()){
            displayResult(result);
            return;
        }
        
        if (byInsert) {
            addRowUserTable(user);
        } else {
            editRowUserTable(user);
        }
        
        if (byInsert) new PasswordForm(rawPassword).setVisible(true);
        
        clearUserSelection();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        _userTableModel = (DefaultTableModel)tbl_list.getModel();                       
        
        userTableEvents();
        clearUserTable();
        clearUserSelection();
        
        ResultData<ArrayList<User>> result = _usersController.getAll();
        if (result.hasError()){
            displayResult(Result.error(result.getErrorMessage()));
            return;
        }
        
        for (User user : result.getData()) {
            addRowUserTable(user);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearUserSelection();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_trashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trashActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Deseja excluir o usuário?", "Excluir", JOptionPane.YES_NO_OPTION);
        if(option != JOptionPane.OK_OPTION) return;
        User user = getUser();
        Result result = _usersController.delete(user.getId());
        if (result.hasError()) {
            displayResult(result);
            return;        
        }
        
        removeRowUserTable(user);
        clearUserSelection();
    }//GEN-LAST:event_btn_trashActionPerformed

    private void btn_change_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_keyActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Deseja gerar uma nova senha para o usuário?", "Excluir", JOptionPane.YES_NO_OPTION);
        if(option != JOptionPane.OK_OPTION) return;
        User user = getUser();
        String randomPassword = _usersController.generatePassword();
        Result result = _usersController.resetPassword(user.getId(), randomPassword);
        if (result.hasError()) {
            displayResult(result);
            return;        
        }
        
        new PasswordForm(randomPassword).setVisible(true);
        
        clearUserSelection();
    }//GEN-LAST:event_btn_change_keyActionPerformed
    
    private void clearUserTable() {
        _userTableModel.setRowCount(0);
    }
    
    private void clearUserSelection() {
        btn_trash.setEnabled(false);
        btn_change_key.setEnabled(false);
        tbl_list.clearSelection();
        setUser(new User());  
    }
    
    private void userTableEvents() {
        ListSelectionModel model = tbl_list.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = tbl_list.getSelectedRow();
                if (row == -1) {
                    setUser(new User());
                    return;
                }
                int id = getTableIdByIndex(_userTableModel, row);
                ResultData<User> result = _usersController.getById(id);
                if (result.hasError()){
                    displayResult(Result.error(result.getErrorMessage()));
                    return;
                }
                btn_trash.setEnabled(true);
                btn_change_key.setEnabled(true);
                setUser(result.getData());
            }
        });
    }
    
    private int getTableIdByIndex(DefaultTableModel model, int index) {
        Object raw = model.getValueAt(index, 0);
        return Integer.parseInt(raw.toString());
    }
    
    private void displayResult(Result result) {
        JOptionPane.showMessageDialog(this, result.getErrorMessage(), "Informação", JOptionPane.INFORMATION_MESSAGE);
    }    
    
    private ArrayList<Object> getUserColumnsData(User user) {
        ArrayList<Object> columns = new ArrayList<>();
        columns.add(user.getId());
        columns.add(user.getName());
        columns.add(user.getEmail());
        columns.add(user.getLogin());
        return columns;
    }
    
    private void addRowUserTable(User user) {
        ArrayList<Object> columnsData = getUserColumnsData(user);
        _userTableModel.addRow(columnsData.toArray());
    }
    
    private void editRowUserTable(User user) {
        ArrayList<Object> columnsData = getUserColumnsData(user);
        int row = getRowIndexWithId(_userTableModel, user.getId());
        for (Object data : columnsData){
            int col = columnsData.indexOf(data);
            _userTableModel.setValueAt(data, row, col);
        }
    }
    
    private void removeRowUserTable(User user) {
        int index = getRowIndexWithId(_userTableModel, user.getId());
        _userTableModel.removeRow(index);
    }
    
    private int getRowIndexWithId(DefaultTableModel model, int id) {
        for (int row = 0; row < model.getRowCount(); row++){
            Object raw = model.getValueAt(row, 0);
            int rowId = Integer.parseInt(raw.toString());
            if (rowId == id) return row;
        }
        return -1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change_key;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_trash;
    private javax.swing.JComboBox<SelectRole> cb_role;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JScrollPane list_scroll;
    private javax.swing.JPanel pnl_actions;
    private javax.swing.JPanel pnl_fields;
    private javax.swing.JTable tbl_list;
    private java.awt.TextField txt_email;
    private java.awt.TextField txt_login;
    private java.awt.TextField txt_name;
    // End of variables declaration//GEN-END:variables
}
